version: 1.0.{build}

build:
  verbosity: minimal

environment:
  matrix:
  - PREMAKE_GENERATOR: vs2019
    BUILD_TYPE: Final
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

# before_build:
#   - cmd: git submodule update --init --recursive

build_script:
  - cmd: tools\premake5.exe "%PREMAKE_GENERATOR%" --MM1_GAME_DIRECTORY="%cd%/build/output/" --ARTS_DISABLE_DDRAW
  - cmd: msbuild -verbosity:minimal -nologo -m /p:Configuration="%BUILD_TYPE%" /p:Platform=Win32 "build/Open1560.sln"

artifacts:
  - path: build/output
    name: Open1560-%APPVEYOR_BUILD_NUMBER%
    type: zip

notifications:
  - provider: Webhook
    url:
      secure:
        JoaoTiRGqtWDIW93w8MG7MyH8l9eYLgte1hqzo+ITl6yg7iXC/twHIWy2IHA1exnXJztC+njDQ0S8HNff7NM0uh2hYLkjt/6ZwwSULDDiU6mL2Sa9nysguYuKBDyoRqHI4bNA4i5CZ6sowTTuNHWIiphBO03elKdc4NyMWfabzs=
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
    body: >-
      {
          "username": "The Loaf of Questionable Freshness",
          "avatar_url": "https://i.imgur.com/rFiONCa.png",
          "embeds": [
              {
                  "color": {{#passed}}3066993{{/passed}}{{^passed}}15158332{{/passed}},
                  "author": {
                      "name": "{{projectName}} - Build {{buildVersion}} {{status}}.",
                      "url": "{{buildUrl}}"
                  },
                  "title": "{{commitMessage}}",
                  "url": "{{commitUrl}}",
                  {{#commitMessageExtended}}"description": "```text\n{{commitMessageExtended}}\n```",{{/commitMessageExtended}}
                  "fields": [
                      {
                          "name": "Commit",
                          "value": "[{{commitId}}]({{commitUrl}}) by {{commitAuthorUsername}}",
                          "inline": true
                      },
                      {
                          "name": "Branch",
                          "value": "[{{branch}}](https://github.com/{{repositoryName}}/tree/{{branch}})",
                          "inline": true
                      }{{#jobs.0.passed}},
                      {
                          "name": "Download",
                          "value": "[{{jobs.0.artifacts.0.fileName}}]({{jobs.0.artifacts.0.permalink}})",
                          "inline": true
                      }{{/jobs.0.passed}}
                  ]
              }
          ]
      }
