arts_component "mmwidget"
    files {
        -- "bm_button.cpp",
        "bm_button.h",
        -- "bm_label.cpp",
        "bm_label.h",
        -- "button.cpp",
        "button.h",
        -- "compbase.cpp",
        "compbase.h",
        -- "compcr.cpp",
        "compcr.h",
        -- "compdrec.cpp",
        "compdrec.h",
        -- "comproster.cpp",
        "comproster.h",
        -- "comprrec.cpp",
        "comprrec.h",
        -- "compscroll.cpp",
        "compscroll.h",
        -- "controlwidget.cpp",
        "controlwidget.h",
        "cwarray.cpp",
        "cwarray.h",
        "dropdown.cpp",
        "dropdown.h",
        -- "icon.cpp",
        "icon.h",
        -- "iconwidget.cpp",
        "iconwidget.h",
        -- "label.cpp",
        "label.h",
        "manager.cpp",
        "manager.h",
        "menu.cpp",
        "menu.h",
        -- "mexbutton.cpp",
        "mexbutton.h",
        "mstore.cpp",
        "mstore.h",
        -- "navbar.cpp",
        "navbar.h",
        -- "pointer.cpp",
        "pointer.h",
        -- "slider.cpp",
        "slider.h",
        -- "sliderbar.cpp",
        "sliderbar.h",
        -- "tdwidget.cpp",
        "tdwidget.h",
        -- "textdrop.cpp",
        "textdrop.h",
        -- "textfield.cpp",
        "textfield.h",
        -- "textroller.cpp",
        "textroller.h",
        -- "textroller2.cpp",
        "textroller2.h",
        -- "toggle.cpp",
        "toggle.h",
        -- "toggle2.cpp",
        "toggle2.h",
        -- "togglebutton.cpp",
        "togglebutton.h",
        -- "togglebutton2.cpp",
        "togglebutton2.h",
        -- "tscroll.cpp",
        "tscroll.h",
        -- "ttip.cpp",
        "ttip.h",
        -- "vscrollbar.cpp",
        "vscrollbar.h",
        -- "vswidget.cpp",
        "vswidget.h",
        -- "widget.cpp",
        "widget.h",
        "wstore.cpp",
        "wstore.h",
    }
