arts_component "agiworld"
    files {
        -- "bone.cpp",
        -- "bone.h",
        -- "getmesh.cpp",
        -- "getmesh.h",
        -- "getmodel.cpp",
        -- "getmodel.h",
        -- "meshlight.cpp",
        -- "meshlight.h",
        -- "meshload.cpp",
        -- "meshload.h",
        -- "meshmodel.cpp",
        -- "meshmodel.h",
        "meshrend.cpp",
        "meshrend.h",
        -- "meshsave.cpp",
        -- "meshsave.h",
        -- "meshset.cpp",
        -- "meshset.h",
        -- "mrkni.cpp",
        -- "mrkni.h",
        -- "packnorm.cpp",
        -- "packnorm.h",
        -- "quality.cpp",
        -- "quality.h",
        -- "skeleton.cpp",
        -- "skeleton.h",
        -- "texsheet.cpp",
        -- "texsheet.h",
        "texsort.cpp",
        "texsort.h",
    }
