arts_component "mmgame"
    files {
        -- "cd.cpp",
        -- "cd.h",
        -- "dash.cpp",
        -- "dash.h",
        "game.cpp",
        "game.h",
        -- "gameedit.cpp",
        -- "gameedit.h",
        "gameman.cpp",
        "gameman.h",
        "gamemulti.cpp",
        "gamemulti.h",
        -- "gamesingle.cpp",
        -- "gamesingle.h",
        -- "gauge.cpp",
        -- "gauge.h",
        "hud.cpp",
        "hud.h",
        "hudmap.cpp",
        "hudmap.h",
        -- "icons.cpp",
        -- "icons.h",
        "interface.cpp",
        "interface.h",
        -- "mmambientaudio.cpp",
        -- "mmambientaudio.h",
        -- "multiblitz.cpp",
        -- "multiblitz.h",
        -- "multicircuit.cpp",
        -- "multicircuit.h",
        -- "multicr.cpp",
        -- "multicr.h",
        -- "multirace.cpp",
        -- "multirace.h",
        -- "netobject.cpp",
        -- "netobject.h",
        -- "player.cpp",
        -- "player.h",
        -- "popup.cpp",
        -- "popup.h",
        -- "rainaudio.cpp",
        -- "rainaudio.h",
        -- "singleblitz.cpp",
        -- "singleblitz.h",
        -- "singlecircuit.cpp",
        -- "singlecircuit.h",
        -- "waypoints.cpp",
        -- "waypoints.h",
        -- "wphud.cpp",
        -- "wphud.h",
        -- "wpinst.cpp",
        -- "wpinst.h",
        -- "wpobject.cpp",
        -- "wpobject.h",
    }
