arts_component "arts7"
    files {
        "bank.cpp",
        "bank.h",
        "benchstats.cpp",
        "benchstats.h",
        "camera.cpp",
        "camera.h",
        "cullable.cpp",
        "cullable.h",
        "cullmgr.cpp",
        "cullmgr.h",
        -- "dof.cpp",
        -- "dof.h",
        -- "form.cpp",
        -- "form.h",
        -- "lamp.cpp",
        -- "lamp.h",
        "linear.cpp",
        "linear.h",
        "midgets.cpp",
        "midgets.h",
        "node.cpp",
        "node.h",
        "pgraph.cpp",
        "pgraph.h",
        "sim.cpp",
        "sim.h",
        -- "view.cpp",
        -- "view.h",

        "bank.h",
    }
