/*
    Open1560 - An Open Source Re-Implementation of Midtown Madness 1 Beta
    Copyright (C) 2020 Brick

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

// clang-format off

X(MM_IDS_HELLO, "Hallo")
X(MM_IDS_WORLD, "Welt")
X(MM_IDS_3, "KI-Streckenset wird geladen...")
X(MM_IDS_4, "Straßenkarte wird erstellt...")
X(MM_IDS_5, "Renndatendateien werden geladen...")
X(MM_IDS_6, "Gegner werden erstellt...")
X(MM_IDS_7, "Polizei wird erstellt...")
X(MM_IDS_8, "Umgebungen werden erstellt...")
X(MM_IDS_9, "Fußgänger werden erstellt...")
X(MM_IDS_10, "Kollisions-KI wird initialisiert...")
X(MM_IDS_11, "KI wird zurückgesetzt...")
X(MM_IDS_12, "Stadtlayout wird geladen...")
X(MM_IDS_13, "Klapperkisten werden geladen...")
X(MM_IDS_14, "Fassaden werden geladen...")
X(MM_IDS_15, "Gill Sans MT, 12, 24, 0, 400")
X(MM_IDS_16, "Gill Sans MT, 12, 16, 0, 400")
X(MM_IDS_17, "%d%% abgeschlossen...")
X(MM_IDS_18, "Statisches Gelände wird geladen...")
X(MM_IDS_19, "Eingangsdaten werden geladen...")
X(MM_IDS_20, "Kollisionsdatenbank wird geladen...")
X(MM_IDS_PLAYER_NAME, "Spieler")
X(MM_IDS_LOADING_AUDIO, "Audio wird geladen...")
X(MM_IDS_LOADING_CITY, "Stadt wird geladen...")
X(MM_IDS_LOADING_PLAYER, "Spieler wird geladen...")
X(MM_IDS_LOADING_AI, "KI wird geladen...")
X(MM_IDS_OPP_NAME, "Gegner %d")
X(MM_IDS_LOADING_MORE_AUDIO, "Weitere Audiodaten werden geladen...")
X(MM_IDS_CIRCUIT_RACE, "Rundkursrennen")
X(MM_IDS_CHECKPOINT_RACE, "Kontrollpunktrennen")
X(MM_IDS_BLITZ_RACE, "Blitzrennen")
X(MM_IDS_CNR_FREE_FOR_ALL, "Jeder gegen Jeden")
X(MM_IDS_CNR_COPS_N_ROBBERS, "Polizei und Gangster")
X(MM_IDS_CNR_ROBBERS_TEAMS, "Gangsterteams")
X(MM_IDS_COPS_N_ROBBERS, "Polizei und Gangster")
X(MM_IDS_35, "Gegner 1")
X(MM_IDS_36, "Gegner 2")
X(MM_IDS_37, "Gegner3")
X(MM_IDS_38, "Gegner 4")
X(MM_IDS_39, "Gegner 5")
X(MM_IDS_40, "Gegner 6")
X(MM_IDS_41, "Gegner 7")
X(MM_IDS_42, "Gegner 8")
X(MM_IDS_43, "Erster!")
X(MM_IDS_44, "wurde Zweiter")
X(MM_IDS_45, "wurde Dritter")
X(MM_IDS_46, "wurde Vierter")
X(MM_IDS_47, "wurde Fünfter")
X(MM_IDS_48, "wurde Sechster")
X(MM_IDS_49, "wurde Siebter")
X(MM_IDS_50, "wurde Achter")
X(MM_IDS_51, "Das kann nicht wahr sein!")
X(MM_IDS_52, "Schlaf bei den Fischen!")
X(MM_IDS_53, "Warten auf 1 Spieler")
X(MM_IDS_54, "Warten auf 2 Spieler")
X(MM_IDS_55, "Warten auf 3 Spieler")
X(MM_IDS_56, "Warten auf 4 Spieler")
X(MM_IDS_57, "Warten auf 5 Spieler")
X(MM_IDS_58, "Warten auf 6 Spieler")
X(MM_IDS_59, "Warten auf 7 Spieler")
X(MM_IDS_60, "hat das Spiel verlassen.")
X(MM_IDS_61, "Der Host hat das Spiel verlassen.")
X(MM_IDS_62, "ist hinzugekommen.")
X(MM_IDS_63, "Sie wurden hinausgeworfen.")
X(MM_IDS_64, "Laden der Remotespieler...")
X(MM_IDS_65, "Gill Sans MT, 16, 32, 0, 400")
X(MM_IDS_66, "Sie sind Erster!")
X(MM_IDS_67, "Sie sind Zweiter.")
X(MM_IDS_68, "Sie sind Dritter.")
X(MM_IDS_69, "Sie sind Vierter.")
X(MM_IDS_70, "Sie sind Fünfter.")
X(MM_IDS_71, "Sie sind Sechster.")
X(MM_IDS_72, "Sie sind Siebter.")
X(MM_IDS_73, "Sie sind Achter.")
X(MM_IDS_74, "Sie sind eine lahme Ente.")
X(MM_IDS_75, "Bereit...")
X(MM_IDS_76, "Festlegen...")
X(MM_IDS_77, "LOS!!")
X(MM_IDS_78, "Ende des Spiels!")
X(MM_IDS_79, "Sie sind Erster!")
X(MM_IDS_80, "Sie sind Zweiter")
X(MM_IDS_81, "Sie sind Dritter")
X(MM_IDS_82, "Sie sind Vierter")
X(MM_IDS_83, "Sie sind Fünfter")
X(MM_IDS_84, "Sie sind Sechster")
X(MM_IDS_85, "Sie sind Siebter")
X(MM_IDS_86, "Sie sind Achter")
X(MM_IDS_87, "Sie sind eine lahme Ente.")
X(MM_IDS_88, "Sie haben sich gerade den Panoz GTR-1 verdient!!!")
X(MM_IDS_89, "Sind Sie verrückt? Sie haben den Stadtbus frei gegeben!!!")
X(MM_IDS_90, "Sie haben den Ford Mustang Cruiser  frei gegeben!")
X(MM_IDS_91, "Sie haben die nächste Rennserie frei gegeben!!!")
X(MM_IDS_92, "Glückwunsch! Versuchen Sie jetzt den PROFI-MODUS!")
X(MM_IDS_93, "Glückwunsch! Sie haben alle Kontrollpunktrennen geschafft!!!")
X(MM_IDS_94, "Broadway")
X(MM_IDS_95, "Gill Sans MT, 12, 24, 0, 400")
X(MM_IDS_96, "Gill Sans MT, 20, 36, 0, 400")
X(MM_IDS_97, "Gill Sans MT, 8, 16, 0, 400")
X(MM_IDS_98, "---")
X(MM_IDS_99, "DriverX")
X(MM_IDS_100, "DriverX")
X(MM_IDS_101, "Möchten Sie an einem laufenden Spiel teilnehmen oder selbst eines ausrichten?")
X(MM_IDS_102, "ist hinzugekommen.")
X(MM_IDS_103, "hat das Spiel verlassen.")
X(MM_IDS_104, "**Der Host hat das Spiel verlassen.**")
X(MM_IDS_105, "http://www.zone.com/asp/midtredir.asp")
X(MM_IDS_106, "Klicken Sie bitte auf das Midtown Madness-Symbol in der Taskleiste, wenn Sie die Verbindung zum Internet überprüft haben.")
X(MM_IDS_107, "Klicken Sie bitte auf das Midtown Madness-Symbol in der Taskleiste, wenn Sie die Verbindung zum Internet überprüft haben.")
X(MM_IDS_108, "Namenlos")
X(MM_IDS_109, "Polizei und Gangster")
X(MM_IDS_110, "Tour")
X(MM_IDS_111, "Profi")
X(MM_IDS_112, "Amateur")
X(MM_IDS_113, "FEHLER: Hostort nicht installiert.")
X(MM_IDS_114, "FEHLER: Netzwerkversionen sind inkompatibel.")
X(MM_IDS_115, "Bereit...")
X(MM_IDS_116, "Festlegen...")
X(MM_IDS_117, "LOS!!")
X(MM_IDS_118, "Warten...5 Sekunden Strafe!")
X(MM_IDS_119, "Zeit ist um!")
X(MM_IDS_120, "Ziel erreicht in")
X(MM_IDS_121, "Zeit ist um!")
X(MM_IDS_122, "Der Host hat das Spiel verlassen.")
X(MM_IDS_123, "Bereit...")
X(MM_IDS_124, "Festlegen...")
X(MM_IDS_125, "LOS!!")
X(MM_IDS_126, "Warten...5 Sekunden Strafe!")
X(MM_IDS_127, "Ziel erreicht in")
X(MM_IDS_128, "Zeit ist um!")
X(MM_IDS_129, "Der Host hat das Spiel verlassen.")
X(MM_IDS_130, "Sie haben das Gold verloren!")
X(MM_IDS_131, "LOS!!")
X(MM_IDS_132, "Warten...5 Sekunden Strafe!")
X(MM_IDS_133, "Sie haben das GOLD!")
X(MM_IDS_134, "GOLD ÜBERREICHT!")
X(MM_IDS_135, "GOLD ÜBERREICHT!")
X(MM_IDS_136, "Zeit ist um!")
X(MM_IDS_137, "Zeitpunkt erreicht")
X(MM_IDS_138, "Zeitpunkt erreicht")
X(MM_IDS_139, "Zeitpunkt erreicht")
X(MM_IDS_140, "POLIZEI")
X(MM_IDS_141, "GANGSTER")
X(MM_IDS_142, "BLAU")
X(MM_IDS_143, "ROT")
X(MM_IDS_144, "GANGSTER")
X(MM_IDS_145, "POLIZEI")
X(MM_IDS_146, "BLAU")
X(MM_IDS_147, "ROT")
X(MM_IDS_148, "Zeit ist um!")
X(MM_IDS_149, "Zeitpunkt erreicht")
X(MM_IDS_150, "Der Host hat das Spiel verlassen.")
X(MM_IDS_151, "hat das Gold!")
X(MM_IDS_152, "Sie haben das GOLD!")
X(MM_IDS_153, "hat das Gold!")
X(MM_IDS_154, "hat das Gold verfehlt!")
X(MM_IDS_155, "hat das Gold übergeben!")
X(MM_IDS_156, "Noch 20 Minuten.")
X(MM_IDS_157, "Noch 15 Minuten.")
X(MM_IDS_158, "Noch 10 Minuten.")
X(MM_IDS_159, "Noch 5 Minuten.")
X(MM_IDS_160, "Noch 1 Minute.")
X(MM_IDS_161, "LOS!!")
X(MM_IDS_162, "Warten...5 Sekunden Strafe!")
X(MM_IDS_163, "Bereit...")
X(MM_IDS_164, "Festlegen...")
X(MM_IDS_165, "LOS!!")
X(MM_IDS_166, "Warten...5 Sekunden Strafe!")
X(MM_IDS_167, "beschädigt ausgeschieden")
X(MM_IDS_168, "Ziel erreicht in")
X(MM_IDS_169, "Zeit ist um!")
X(MM_IDS_170, "Der Host hat das Spiel verlassen.")
X(MM_IDS_171, "Bereit...")
X(MM_IDS_172, "Festlegen...")
X(MM_IDS_173, "LOS!!")
X(MM_IDS_174, "Zeit ist um!")
X(MM_IDS_175, "Ende des Spiels!")
X(MM_IDS_176, "Steigen Sie in den Panoz GTR-1!!!")
X(MM_IDS_177, "Nehmen Sie alle Freunde auf eine Fahrt im Stadtbus mit!!!")
X(MM_IDS_178, "Sie haben die fürchterlichen kräfte des Freightliner Century freigesetzt!")
X(MM_IDS_179, "Sie haben alle Blitzrennen gewonnen!")
X(MM_IDS_180, "Sie haben gewonnen!")
X(MM_IDS_181, "Bereit...")
X(MM_IDS_182, "Festlegen...")
X(MM_IDS_183, "LOS!!")
X(MM_IDS_184, "Warten...5 Sekunden Strafe!")
X(MM_IDS_185, "Sie sind Erster!")
X(MM_IDS_186, "Sie sind Zweiter.")
X(MM_IDS_187, "Sie sind Dritter.")
X(MM_IDS_188, "Sie sind Vierter.")
X(MM_IDS_189, "Sie sind Fünfter.")
X(MM_IDS_190, "Sie sind Sechster.")
X(MM_IDS_191, "Sie sind Siebter.")
X(MM_IDS_192, "Sie sind Achter.")
X(MM_IDS_193, "Sie sind eine lahme Ente.")
X(MM_IDS_194, "Nehmen Sie den Panoz GTR-1 zum Drehen. Sie haben ihn sich verdient.")
X(MM_IDS_195, "Wer braucht es passend? Jetzt können Sie den Stadtbus FAHREN.")
X(MM_IDS_196, "Sie haben sich den Ford Mustang Fastback verdient")
X(MM_IDS_197, "Sie sind ja verrückt! Sie haben alle Rundkursrennen gewonnen!")
X(MM_IDS_USE_HIGH_COLOR, "Stellen Sie Ihren Desktop bitte auf  High Color (16 Bit)-Modus um, bevor Sie Midtown Madness starten.")
X(MM_IDS_REDETECT_VIDEO, "Führen Sie bitte Redetect Video (in Ihrem Midtown Madness-Ordner) aus, und wählen Sie in 'Grafikoptionen' (Menü 'Optionen') einen anderen Renderer aus.")
X(MM_IDS_GRAPHICS_ERROR, "Fehler beim Einrichten der Grafikkarte gefunden.")
X(MM_IDS_ALREADY_RUNNING, "Midtown Madness wird bereits ausgeführt. Bitte aktivieren Sie das Spiel über die Taskleiste.")
X(MM_IDS_LOW_MEMORY, "Ihr Computer besitzt nicht genügend virtuellen Speicher, um dieses Spiel auszuführen. Dadurch läuft Midtown Madness evtl. ruckartig ab oder reagiert nicht mehr. Um das Problem zu beheben, schaffen Sie freien Festplattenspeicher oder ändern Sie Ihre Einstellungen für den virtuellen Speicher (Zeigen Sie im Windows Startmenü auf 'Einstellungen', klicken Sie auf 'Systemsteuerung', doppelklicken Sie auf 'System', und klicken Sie dann auf die Registerkarte 'Leistungsmerkmale').")
X(MM_IDS_LOW_DISK, "Sie besitzen fast keinen freien Festplattenspeicher mehr.  Midtown Madness kann möglicherweise keine Spieler- oder Renndaten speichern.  Schaffen Sie weiteren freien Festplattenspeicher.")
X(MM_IDS_LOW_VRAM, "Für diese Bildschirmauflösung und/oder Detailauflösung ist mehr Videospeicher erforderlich.  Probieren Sie bitte unterschiedliche Einstellungen in 'Grafikoptionen' (Menü 'Optionen') aus.")
X(MM_IDS_LOADING_GRAPHICS, "Grafiken werden initialisiert...")
X(MM_IDS_LOADING_INTERFACE, "Benutzeroberfläche wird geladen...")
X(MM_IDS_LOADING_RACE, "Rennen wird geladen...")
X(MM_IDS_208, "Kontrollpunkt 1")
X(MM_IDS_209, "Kontrollpunkt 2")
X(MM_IDS_210, "Kontrollpunkt 3")
X(MM_IDS_211, "Kontrollpunkt 4")
X(MM_IDS_212, "Kontrollpunkt 5")
X(MM_IDS_213, "Kontrollpunkt 6")
X(MM_IDS_214, "Kontrollpunkt 7")
X(MM_IDS_215, "Kontrollpunkt 8")
X(MM_IDS_216, "Kontrollpunkt 9")
X(MM_IDS_217, "Kontrollpunkt 10")
X(MM_IDS_218, "Kontrollpunkt 11")
X(MM_IDS_219, "Kontrollpunkt 12")
X(MM_IDS_220, "Kontrollpunkt 13")
X(MM_IDS_221, "Kontrollpunkt 14")
X(MM_IDS_222, "Kontrollpunkt 15")
X(MM_IDS_223, "Kontrollpunkt 16")
X(MM_IDS_224, "Kontrollpunkt 17")
X(MM_IDS_225, "Kontrollpunkt 18")
X(MM_IDS_226, "Kontrollpunkt 19")
X(MM_IDS_227, "Kontrollpunkt 20")
X(MM_IDS_228, "Rundenzeit")
X(MM_IDS_229, "Letzte Runde!")
X(MM_IDS_230, "Gill Sans MT, 16, 22, 0, 700")
X(MM_IDS_231, "Gill Sans MT, 20, 40, 0, 700")
X(MM_IDS_232, "Gill Sans MT, 16, 22, 0, 700")
X(MM_IDS_233, "Platz:  ")
X(MM_IDS_234, "Kontroll:   ")
X(MM_IDS_235, "Gill Sans MT, 16, 22, 0, 700")
X(MM_IDS_236, "Gill Sans MT, 20, 40, 0, 700")
X(MM_IDS_237, "Gill Sans MT, 16, 22, 0, 700")
X(MM_IDS_238, "Platz:  ")
X(MM_IDS_239, "Kontroll: ")
X(MM_IDS_240, "Runde:  ")
X(MM_IDS_241, "Gill Sans MT, 12, 20, 0, 700")
X(MM_IDS_242, "Gill Sans MT, 10, 16, 0, 400")
X(MM_IDS_243, "POLIZEI")
X(MM_IDS_244, "GANGSTER")
X(MM_IDS_245, "BLAU")
X(MM_IDS_246, "ROT")
X(MM_IDS_247, "$")
X(MM_IDS_248, "NICHT DEFINIERT")
X(MM_IDS_249, "Taste")
X(MM_IDS_250, "Joy")
X(MM_IDS_251, "Taste:")
X(MM_IDS_USE_DI_KEYS, "0")
X(MM_IDS_253, "Kamera wechseln")
X(MM_IDS_254, "Ansicht von außen")
X(MM_IDS_255, "Kraftübertragung")
X(MM_IDS_256, "Hupe")
X(MM_IDS_257, "Gaspedal")
X(MM_IDS_258, "Bremsen")
X(MM_IDS_259, "Lenkrad")
X(MM_IDS_260, "Nach links lenken")
X(MM_IDS_261, "Nach rechts lenken")
X(MM_IDS_262, "Nach rechts schauen")
X(MM_IDS_263, "Nach links schauen")
X(MM_IDS_264, "Nach hinten schauen")
X(MM_IDS_265, "Nach vorn schauen")
X(MM_IDS_266, "Weitwinkel")
X(MM_IDS_267, "Armaturenbrett ein/aus")
X(MM_IDS_268, "Hochschalten")
X(MM_IDS_269, "Herunterschalten")
X(MM_IDS_270, "Rückwärtsgang")
X(MM_IDS_271, "Nächste Wegmarke")
X(MM_IDS_272, "Vorh. Wegmarke")
X(MM_IDS_273, "Umschalten Karte")
X(MM_IDS_274, "Umschalten HUD")
X(MM_IDS_275, "Karte als Vollbild")
X(MM_IDS_276, "Kartenauflösung")
X(MM_IDS_277, "Umschalten CD-Player")
X(MM_IDS_278, "CD starten/stoppen")
X(MM_IDS_279, "Nächster CD-Track")
X(MM_IDS_280, "Vorh. CD-Track")
X(MM_IDS_281, "Rückspiegel")
X(MM_IDS_282, "Kameraschwenk")
X(MM_IDS_283, "Handbremse")
X(MM_IDS_284, "Position des Gegners")
X(MM_IDS_285, "Chatnachr. eingeben")
X(MM_IDS_LEFT_MOUSE_BUTTON, "Linke Maustaste")
X(MM_IDS_RIGHT_MOUSE_BUTTON, "Rechte Maustaste")
X(MM_IDS_MOUSE_X_AXIS, "Maus X-Achse")
X(MM_IDS_MOUSE_Y_AXIS, "Maus Y-Achse")
X(MM_IDS_X_AXIS, "X-Achse")
X(MM_IDS_X_AXIS_LEFT, "X-Achse links")
X(MM_IDS_X_AXIS_RIGHT, "X-Achse rechts")
X(MM_IDS_Y_AXIS, "Y-Achse")
X(MM_IDS_Y_AXIS_UP, "Y-Achse hoch")
X(MM_IDS_Y_AXIS_DOWN, "Y-Achse runter")
X(MM_IDS_Z_AXIS, "Z-Achse")
X(MM_IDS_U_AXIS, "U-Achse")
X(MM_IDS_R_AXIS, "R-Achse")
X(MM_IDS_V_AXIS, "V-Achse")
X(MM_IDS_POV_AXIS, "Blickwinkel-Achse")
X(MM_IDS_301, "UNBEKANNT")
X(MM_IDS_302, "Mono")
X(MM_IDS_303, "Stereo")
X(MM_IDS_304, "Surround (nicht empfohlen)")
X(MM_IDS_305, "Surround")
X(MM_IDS_306, "Stereo FX")
X(MM_IDS_307, "Steuerung")
X(MM_IDS_308, "Gewichtslos")
X(MM_IDS_309, "1/4 Tonne")
X(MM_IDS_310, "1/2 Tonne")
X(MM_IDS_311, "GOLDMASSE")
X(MM_IDS_312, "5 Minuten")
X(MM_IDS_313, "10 Minuten")
X(MM_IDS_314, "20 Minuten")
X(MM_IDS_315, "30 Minuten")
X(MM_IDS_316, "100 Punkte")
X(MM_IDS_317, "250 Punkte")
X(MM_IDS_318, "500 Punkte")
X(MM_IDS_319, "1.000 Punkte")
X(MM_IDS_320, "PUNKTE")
X(MM_IDS_321, "RENNEN")
X(MM_IDS_322, "ZEIT")
X(MM_IDS_323, "FAHRZEUG")
X(MM_IDS_324, "Rennstatistik")
X(MM_IDS_325, "PUNKTESTAND")
X(MM_IDS_326, "ZEIT")
X(MM_IDS_327, "RENNEN")
X(MM_IDS_328, "NAME")
X(MM_IDS_329, "FAHRER")
X(MM_IDS_330, "ZEIT")
X(MM_IDS_331, "FAHRZEUG")
X(MM_IDS_332, "WÄHLEN SIE, OB SIE EIN SPIEL AUSRICHTEN ODER AN EINEM SPIEL TEILNEHMEN MÖCHTEN")
X(MM_IDS_333, "Morgen")
X(MM_IDS_334, "Mittag")
X(MM_IDS_335, "Sonnenuntergang")
X(MM_IDS_336, "Nacht")
X(MM_IDS_337, "Sonnig")
X(MM_IDS_338, "Wolkig")
X(MM_IDS_339, "Regen")
X(MM_IDS_340, "Schnee")
X(MM_IDS_341, "Com1")
X(MM_IDS_342, "Com2")
X(MM_IDS_343, "Com3")
X(MM_IDS_344, "Com4")
X(MM_IDS_345, "9600")
X(MM_IDS_346, "14400")
X(MM_IDS_347, "38400")
X(MM_IDS_348, "56000")
X(MM_IDS_349, "57600")
X(MM_IDS_350, "115200")
X(MM_IDS_351, "128000")
X(MM_IDS_352, "256000")
X(MM_IDS_353, "1 Bit")
X(MM_IDS_354, "1,5 Bit")
X(MM_IDS_355, "2 Bit")
X(MM_IDS_356, "Keine")
X(MM_IDS_357, "XOn/XOff")
X(MM_IDS_358, "RTS")
X(MM_IDS_359, "DTR")
X(MM_IDS_360, "RTS/DTR")
X(MM_IDS_361, "Keine Parität")
X(MM_IDS_362, "Ungerade")
X(MM_IDS_363, "Gerade")
X(MM_IDS_364, "Marke")
X(MM_IDS_365, "PLATZIERUNG:")
X(MM_IDS_366, "LETZTES RENNEN:")
X(MM_IDS_367, "LETZTES FAHRZEUG:")
X(MM_IDS_368, "STEUERUNG:")
X(MM_IDS_369, "NETZNAME:")
X(MM_IDS_370, "PUNKTESTAND:")
X(MM_IDS_371, " - empfohlen")
X(MM_IDS_372, "Niedrig")
X(MM_IDS_373, "Mittel")
X(MM_IDS_374, "Hoch")
X(MM_IDS_375, "Sehr hoch [AGP]")
X(MM_IDS_376, "%d x %d - empfohlen")
X(MM_IDS_377, "Menü Test")
X(MM_IDS_378, "Nachricht hier eingeben. Zum Senden EINGABETASTE drücken.")
X(MM_IDS_379, "Gebietsschema:")
X(MM_IDS_380, "Wetter: klar")
X(MM_IDS_381, "Wetter: neblig")
X(MM_IDS_382, "Wetter: Regen")
X(MM_IDS_383, "Wetter: Schnee")
X(MM_IDS_384, "Zeit: morgens")
X(MM_IDS_385, "Zeit: mittags")
X(MM_IDS_386, "Zeit: abends")
X(MM_IDS_387, "Zeit: nachts")
X(MM_IDS_388, "Schwierigkeitsgrad: Amateur")
X(MM_IDS_389, "Schwierigkeitsgrad: Profi")
X(MM_IDS_390, "Runden")
X(MM_IDS_391, "Kontrollpunkte")
X(MM_IDS_392, "Fahrer: ")
X(MM_IDS_393, "Fahrzeug: ")
X(MM_IDS_394, "Farbe: ")
X(MM_IDS_395, "Spieler der Sitzung")
X(MM_IDS_396, "warten, dass der Host beginnt...")
X(MM_IDS_397, "Rennen starten")
X(MM_IDS_398, "warten, dass der Host beginnt...")
X(MM_IDS_399, "Dienstanbieter auswählen")
X(MM_IDS_400, ".....")
X(MM_IDS_401, "Namenlos")
X(MM_IDS_402, "Wählen Sie die Spielsitzung aus, an der Sie teilnehmen möchten.")
X(MM_IDS_403, "Netzauswahl 2")
X(MM_IDS_404, "Sitzung erstellen")
X(MM_IDS_405, "An Sitzung teilnehmen")
X(MM_IDS_406, "Audiooptionen")
X(MM_IDS_407, "Wavelautstärke")
X(MM_IDS_408, "CD-Lautstärke")
X(MM_IDS_409, "Balance")
X(MM_IDS_410, "MENÜ 'CHAT'")
X(MM_IDS_412, "Steuerungsoptionen")
X(MM_IDS_413, "Steuerungsempfindlichkeit")
X(MM_IDS_414, "Tote Zone für Steuerung")
X(MM_IDS_415, "Force-Feedback-Skala")
X(MM_IDS_416, "Straßenkräfte-Skala")
X(MM_IDS_417, "STEUERUNG")
X(MM_IDS_418, "DEBUG")
X(MM_IDS_419, "Pos. aufzeichnen")
X(MM_IDS_420, "MENÜ 'BEENDEN'")
X(MM_IDS_421, "MÖCHTEN SIE DAS SPIEL BEENDEN?")
X(MM_IDS_422, "Ja")
X(MM_IDS_423, "Nein")
X(MM_IDS_424, "Grafik")
X(MM_IDS_425, "SCHATTEN")
X(MM_IDS_426, "OBJEKTDETAILS")
X(MM_IDS_427, "WEITSICHT")
X(MM_IDS_428, "LICHTQUALITÄT")
X(MM_IDS_429, "Wolkenschatten")
X(MM_IDS_430, "Fahrzeugreflektionen")
X(MM_IDS_431, "Himmelsdetails")
X(MM_IDS_432, "Mit Zeilensprung")
X(MM_IDS_433, "Filter für beste Details")
X(MM_IDS_PU_KEYS_NAME, "FUNKTIONSDARSTELLUNG")
X(MM_IDS_PU_MAIN_NAME, "HAUPTMENÜ")
X(MM_IDS_PU_MAIN_RESTART, "Rennen neu starten")
X(MM_IDS_PU_MAIN_OPTIONS, "Optionen")
X(MM_IDS_PU_MAIN_HELP, "Hilfe")
X(MM_IDS_PU_MAIN_QUIT, "Zum Menü Rennen wechseln")
X(MM_IDS_PU_MAIN_EXIT, "Beenden und zu Windows wechseln")
X(MM_IDS_441, "Vorheriges Menü")
X(MM_IDS_442, "Abbrechen")
X(MM_IDS_443, "OK")
X(MM_IDS_444, "Menü beenden")
X(MM_IDS_445, "Optionen")
X(MM_IDS_446, "Audiooptionen")
X(MM_IDS_447, "Steuerungsoptionen")
X(MM_IDS_448, "Grafikoptionen")
X(MM_IDS_449, "MENÜ 'BEENDEN'")
X(MM_IDS_450, "MÖCHTEN SIE DAS RENNEN VERLASSEN?")
X(MM_IDS_451, "Ja")
X(MM_IDS_452, "Nein")
X(MM_IDS_PU_RESULTS_NAME, "Ergebnisse")
X(MM_IDS_PU_RESULTS_RESTART, "Rennen neu starten")
X(MM_IDS_PU_RESULTS_NEXT, "Nächstes Rennen")
X(MM_IDS_PU_RESULTS_ROSTER, "Spieleraufstellung anzeigen")
X(MM_IDS_PU_RESULTS_QUIT, "Menü 'Rennen'")
X(MM_IDS_PU_RESULTS_EXIT, "Beenden und zu Windows wechseln")
X(MM_IDS_459, "Aufstellung")
X(MM_IDS_460, "Host")
X(MM_IDS_461, "Polizist")
X(MM_IDS_462, "Gangster")
X(MM_IDS_463, "Rot")
X(MM_IDS_464, "Blau")
X(MM_IDS_465, "0")
X(MM_IDS_466, "Gill Sans MT, 16, 16, 0, 400")
X(MM_IDS_467, "Gill Sans MT, 16, 16, 0, 400")
X(MM_IDS_468, "Gill Sans MT, 16, 16, 0, 400")
X(MM_IDS_469, "Gill Sans MT, 16, 20, 0, 400")
X(MM_IDS_470, "Gill Sans MT, 16, 24, 0, 400")
X(MM_IDS_471, "Gill Sans MT, 16, 32, 0, 400")
X(MM_IDS_472, "Gill Sans MT, 24, 48, 0, 400")
X(MM_IDS_473, "Gill Sans MT, 32, 64, 0, 400")
X(MM_IDS_474, "Gill Sans MT, 16, 16, 0, 400")
X(MM_IDS_475, "Gill Sans MT, 16, 16, 0, 400")
X(MM_IDS_476, "Gill Sans MT, 16, 16, 0, 400")
X(MM_IDS_477, "Gill Sans MT, 16, 20, 0, 400")
X(MM_IDS_478, "Gill Sans MT, 16, 24, 0, 400")
X(MM_IDS_479, "Gill Sans MT, 20, 18, 0, 400")
X(MM_IDS_480, "Gill Sans MT, 20, 40, 0, 400")
X(MM_IDS_481, "Gill Sans MT, 32, 64, 0, 400")
X(MM_IDS_482, "Niedrig")
X(MM_IDS_483, "Mittel")
X(MM_IDS_484, "Hoch")
X(MM_IDS_485, "Sehr hoch ")
X(MM_IDS_486, "Manuell")
X(MM_IDS_487, "Automatisch")
X(MM_IDS_488, "Maus")
X(MM_IDS_489, "Tastatur")
X(MM_IDS_490, "Joystick")
X(MM_IDS_491, "Gamepad")
X(MM_IDS_492, "Lenkrad")
X(MM_IDS_493, "Blitz")
X(MM_IDS_494, "Rundkurs")
X(MM_IDS_495, "Kontrollpunkt")
X(MM_IDS_496, "Tour")
X(MM_IDS_497, "Polizei und Gangster")
X(MM_IDS_498, "1")
X(MM_IDS_499, "2")
X(MM_IDS_500, "3")
X(MM_IDS_501, "4")
X(MM_IDS_502, "5")
X(MM_IDS_503, "6")
X(MM_IDS_504, "7")
X(MM_IDS_505, "8")
X(MM_IDS_506, "9")
X(MM_IDS_507, "10")
X(MM_IDS_508, "Keine")
X(MM_IDS_509, "Nur für Fahrzeuge")
X(MM_IDS_510, "Fahrzeuge und Requisiten")
X(MM_IDS_511, "Fahrzeuge, Requisiten  und Bremsspuren")
X(MM_IDS_512, "Navigationsleiste")
X(MM_IDS_513, "0")
X(MM_IDS_514, "AUS")
X(MM_IDS_515, "EIN")
X(MM_IDS_516, "Diese Anwendung benötigt zur Ausführung DirectX 6.1 oder höher.")
X(MM_IDS_517, "320")
X(MM_IDS_518, "200")
X(MM_IDS_519, "Wechseln Sie bitte in einen 16-Bit-Modus, und starten Sie diese Anwendung neu.")
X(MM_IDS_520, "%s")
X(MM_IDS_521, "Es wurde eine '%s'-Videokarte gefunden. Diese wird jedoch nicht unterstützt, da sie nicht genügend Videospeicher besitzt und ihr zu viele 3D-Features fehlen.")
X(MM_IDS_522, "Es wurde eine '%s'-Videokarte gefunden. Diese wird jedoch nicht unterstützt, da ihr zu viele 3D-Features fehlen.")
X(MM_IDS_523, "Es wurde eine '%s'-Videokarte gefunden. Diese wird jedoch nicht unterstützt, da sie nicht mindestens 2 MB Videospeicher besitzt.")
X(MM_IDS_524, "Softwarerenderer")
X(MM_IDS_DETECTING_GPU, "Klicken Sie auf 'OK', um Midtown Madness nach einer Hardwarebeschleunigerkarte suchen zu lassen. Das kann einige Sekunden dauern, während denen Ihr Bildschirm möglicherweise flackert.")
X(MM_IDS_NO_RENDERERS, "Es wurden keine geeigneten Grafikkarten gefunden. Die Anwendung kann nicht ausgeführt werden.")

// clang-format on
