/*
    Open1560 - An Open Source Re-Implementation of Midtown Madness 1 Beta
    Copyright (C) 2020 Brick

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

// clang-format off

X(MM_IDS_HELLO, "Привет")
X(MM_IDS_WORLD, "Мир")
X(MM_IDS_3, "Загружаю информацию о препятствиях...")
X(MM_IDS_4, "Создаю карту дорог...")
X(MM_IDS_5, "Считываю данные о дорогах...")
X(MM_IDS_6, "Создаю оппонентов...")
X(MM_IDS_7, "Создаю полицию...")
X(MM_IDS_8, "Создаю окружение...")
X(MM_IDS_9, "Создаю пешеходов...")
X(MM_IDS_10, "Считываю данные о просшествиях...")
X(MM_IDS_11, "Сброс ИИ...")
X(MM_IDS_12, "Загружаю карту города...")
X(MM_IDS_13, "Загружаю баннеры...")
X(MM_IDS_14, "Загружаю фасады...")
X(MM_IDS_15, "System, 11, 22, 0, 400")
X(MM_IDS_16, "System, 11, 14, 0, 400")
X(MM_IDS_17, "%d%% закончено...")
X(MM_IDS_LOADING_STATIC_TERRAIN, "Загружаю статические объекты...")
X(MM_IDS_LOADING_PORTAL_INFO, "Загружаю порталы...")
X(MM_IDS_LOADING_COLLISION_DATABASE, "Загружаю информацю о происшествиях...")
X(MM_IDS_PLAYER_NAME, "Игрок")
X(MM_IDS_LOADING_AUDIO, "Загружаю звук...")
X(MM_IDS_LOADING_CITY, "Загружаю город...")
X(MM_IDS_LOADING_PLAYER, "Загружаю игрока...")
X(MM_IDS_LOADING_AI, "Загружаю ИИ...")
X(MM_IDS_OPP_NAME, "Opp.%d")
X(MM_IDS_LOADING_MORE_AUDIO, "Загружаю дополнительные звуки...")
X(MM_IDS_CIRCUIT_RACE, "Гонка по кругу")
X(MM_IDS_CHECKPOINT_RACE, "Гонка с отметками")
X(MM_IDS_BLITZ_RACE, "Блиц гонка")
X(MM_IDS_CNR_FREE_FOR_ALL, "Каджый сам по себе")
X(MM_IDS_CNR_COPS_N_ROBBERS, "ГАИ и засранцы")
X(MM_IDS_CNR_ROBBERS_TEAMS, "Команды засранцев")
X(MM_IDS_COPS_N_ROBBERS, "ГАИ и засранцы")
X(MM_IDS_35, "Оппонент 1")
X(MM_IDS_36, "Оппонент 2")
X(MM_IDS_37, "Оппонент 3")
X(MM_IDS_38, "Оппонент 4")
X(MM_IDS_39, "Оппонент 5")
X(MM_IDS_40, "Оппонент 6")
X(MM_IDS_41, "Оппонент 7")
X(MM_IDS_42, "Оппонент 8")
X(MM_IDS_43, "финишировал 1!")
X(MM_IDS_44, "финишировал 2")
X(MM_IDS_45, "финишировал 3")
X(MM_IDS_46, "финишировал 4")
X(MM_IDS_47, "финишировал 5")
X(MM_IDS_48, "финишировал 6")
X(MM_IDS_49, "финишировал 7")
X(MM_IDS_50, "финишировал 8")
X(MM_IDS_51, "Этого не должно было произойти!")
X(MM_IDS_52, "Спи с рыбками!")
X(MM_IDS_53, "Подождите 1 игрока")
X(MM_IDS_54, "Подождите 2 игроков")
X(MM_IDS_55, "Подождите 3 игроков")
X(MM_IDS_56, "Подождите 4 игроков")
X(MM_IDS_57, "Подождите 5 игроков")
X(MM_IDS_58, "Подождите 6 игроков")
X(MM_IDS_59, "Подождите 7 игроков")
X(MM_IDS_60, "вышел из игры.")
X(MM_IDS_61, "Сервер отключился.")
X(MM_IDS_62, "вошел в игру.")
X(MM_IDS_63, "Вас выкинуло.")
X(MM_IDS_64, "Загружаю удаленных игроков...")
X(MM_IDS_65, "System, 14, 30, 0, 400")
X(MM_IDS_66, "Вы финишировали 1!")
X(MM_IDS_67, "Вы финишировали 2.")
X(MM_IDS_68, "Вы финишировали 3.")
X(MM_IDS_69, "Вы финишировали 4.")
X(MM_IDS_70, "Вы финишировали 5.")
X(MM_IDS_71, "Вы финишировали 6.")
X(MM_IDS_72, "Вы финишировали 7.")
X(MM_IDS_73, "Вы финишировали 8.")
X(MM_IDS_74, "Вы бездельник!")
X(MM_IDS_75, "На старт...")
X(MM_IDS_76, "Внимание...")
X(MM_IDS_77, "Гони!!!")
X(MM_IDS_78, "Игра закончена!")
X(MM_IDS_79, "Вы финишировали 1!")
X(MM_IDS_80, "Вы финишировали 2")
X(MM_IDS_81, "Вы финишировали 3")
X(MM_IDS_82, "Вы финишировали 4")
X(MM_IDS_83, "Вы финишировали 5")
X(MM_IDS_84, "Вы финишировали 6")
X(MM_IDS_85, "Вы финишировали 7")
X(MM_IDS_86, "Вы финишировали 8")
X(MM_IDS_87, "Вы бездельник!")
X(MM_IDS_88, "Теперь вы можете кататься на Panoz GTR-1!!!")
X(MM_IDS_89, "Вы рихнулись?  Теперь у вас есть City Bus!!!")
X(MM_IDS_90, "Теперь вас есть Ford Mustang Cruiser!")
X(MM_IDS_91, "Теперь у вас есть доступ с следующим трассам!!!")
X(MM_IDS_92, "Поздравлю!!! Теперь попробуйте себя в прфессиональнос классе.")
X(MM_IDS_93, "Поздравляю!!! Вы прошли все трассы с отметка")
X(MM_IDS_94, "Бродвей")
X(MM_IDS_95, "System, 11, 22, 0, 400")
X(MM_IDS_96, "System, 18, 34, 0, 400")
X(MM_IDS_97, "System, 8, 14, 0, 400")
X(MM_IDS_98, "---")
X(MM_IDS_99, "DriverX")
X(MM_IDS_100, "DriverX")
X(MM_IDS_101, "Вы хотите присоединиться к существующей игре или создать сервер?")
X(MM_IDS_102, "вошел в игру.")
X(MM_IDS_103, "вышел из игры.")
X(MM_IDS_104, "**Сервер отключился**")
X(MM_IDS_105, "http://www.zone.com/asp/midtredir.asp")
X(MM_IDS_106, "Нажмите на иконку игры в списке задач и убедитесь, что вы подключены к Internet.")
X(MM_IDS_107, "Нажмите на иконку игры в списке задач и убедитесь, что вы подключены к Internet.")
X(MM_IDS_108, "без имени")
X(MM_IDS_109, "ГАИ и засранцы")
X(MM_IDS_110, "Прогулка")
X(MM_IDS_111, "Профессионал")
X(MM_IDS_112, "Любитель")
X(MM_IDS_113, "ОШИБКА: Проблемы с сервером.")
X(MM_IDS_114, "ОШИБКА: Проблемы с сетью.")
X(MM_IDS_115, "На старт...")
X(MM_IDS_116, "Внимание...")
X(MM_IDS_117, "Гони!!!")
X(MM_IDS_118, "Подожите...5 штрафных секунд!")
X(MM_IDS_119, "Время вышло!")
X(MM_IDS_120, "финишировал за")
X(MM_IDS_121, "Время вышло!")
X(MM_IDS_122, "Сервер отключился.")
X(MM_IDS_123, "На страт...")
X(MM_IDS_124, "Внимание...")
X(MM_IDS_125, "Гони!!!")
X(MM_IDS_126, "Подожите...5 штрафных секунд!")
X(MM_IDS_127, "финишировал за")
X(MM_IDS_128, "Время вышло!")
X(MM_IDS_129, "Сервер отключился.")
X(MM_IDS_130, "Вы потеряли золото!")
X(MM_IDS_131, "Гони!!!")
X(MM_IDS_132, "Подождите...5 штрафных секунд!")
X(MM_IDS_133, "Вы снова богаты, у вас есть ЗОЛОТО!")
X(MM_IDS_134, "Золото доставлено!")
X(MM_IDS_135, "Золото доставлено!")
X(MM_IDS_136, "Упссс,Время вышло!")
X(MM_IDS_137, "Лимит очков исчерпан")
X(MM_IDS_138, "Лимит очков исчерпан")
X(MM_IDS_139, "Лимит очков исчерпан")
X(MM_IDS_140, "ГАИ")
X(MM_IDS_141, "ЗАСРАНЕЦ")
X(MM_IDS_142, "СИНИЙ")
X(MM_IDS_143, "КРАСНЫЙ")
X(MM_IDS_144, "ЗАСРАНЦЫ")
X(MM_IDS_145, "ГАИ")
X(MM_IDS_146, "СИНИЙ")
X(MM_IDS_147, "КРАСНЫЙ")
X(MM_IDS_148, "Упссс, время вышло!")
X(MM_IDS_149, "Лимит очков исчерпан")
X(MM_IDS_150, "Сервер отключился.")
X(MM_IDS_151, "отхватил ЗОЛОТО!")
X(MM_IDS_152, "ЗОЛОТО у вас!")
X(MM_IDS_153, "отхватил ЗОЛОТО!")
X(MM_IDS_154, "потерял золото!")
X(MM_IDS_155, "доставил золото!")
X(MM_IDS_156, "20 минут")
X(MM_IDS_157, "15 минут")
X(MM_IDS_158, "10 минут")
X(MM_IDS_159, "5 минут")
X(MM_IDS_160, "1 минута")
X(MM_IDS_161, "Гони!!!")
X(MM_IDS_162, "Подождите... 5 штрафных секунд!")
X(MM_IDS_163, "На старт...")
X(MM_IDS_164, "Внимние...")
X(MM_IDS_165, "Гони!!!")
X(MM_IDS_166, "Подождите... 5 штрафных секунд!")
X(MM_IDS_167, "разбит")
X(MM_IDS_168, "финишировал за")
X(MM_IDS_169, "Упссс, время вышло!")
X(MM_IDS_170, "Сервер отключился.")
X(MM_IDS_171, "На старт...")
X(MM_IDS_172, "Внимание...")
X(MM_IDS_173, "Гони!!!")
X(MM_IDS_174, "Упссс, время вышло!")
X(MM_IDS_175, "Игра окончена!")
X(MM_IDS_176, "Пора переходить на Panoz GTR-1!!!")
X(MM_IDS_177, "А не покататься ли тебе с друзьями в City Bus!!!")
X(MM_IDS_178, "Теперь вам доступен Freightliner Century!")
X(MM_IDS_179, "Вы прошли все блиц гонки!!")
X(MM_IDS_180, "Вы выиграли!")
X(MM_IDS_RACE_READY, "На старт...")
X(MM_IDS_RACE_SET, "Внимание...")
X(MM_IDS_RACE_GO, "Гони!!!")
X(MM_IDS_DAMAGE_PENALTY, "Подождите... 5 штрафных секунд!")
X(MM_IDS_185, "Вы финишировали 1!")
X(MM_IDS_186, "Вы финишировали 2.")
X(MM_IDS_187, "Вы финишировали 3.")
X(MM_IDS_188, "Вы финишировали 4.")
X(MM_IDS_189, "Вы финишировали 5.")
X(MM_IDS_190, "Вы финишировали 6.")
X(MM_IDS_191, "Вы финишировали 7.")
X(MM_IDS_192, "Вы финишировали 8.")
X(MM_IDS_193, "Вы бездельник!")
X(MM_IDS_194, "Возьмите себе Panoz GTR-1. Вы заработали ее!")
X(MM_IDS_195, "Теперь вы можете управлять City Bus.")
X(MM_IDS_196, "Ford Mustang Fastback теперь ваш!")
X(MM_IDS_197, "Невероятно! Вы прошли все круговые гонки!")
X(MM_IDS_USE_HIGH_COLOR, "Поставьте разрешение экрана High Color (16-bit) перед стартом игры.")
X(MM_IDS_REDETECT_VIDEO, "В меню 'настройки графики' выберите другой способ тонирования.")
X(MM_IDS_GRAPHICS_ERROR, "Ошибка иницилизации видое карты.")
X(MM_IDS_ALREADY_RUNNING, "Игра уже запущена! Посмотрите в списке задач!")
X(MM_IDS_LOW_MEMORY, "Игре не хватает памяти! Попробуйте выгрузить некоторые задачи.")
X(MM_IDS_LOW_DISK, "У вас практически нет места на жестком диске! Снесите чего-нибудь.")
X(MM_IDS_LOW_VRAM, "Требуется больше видео памяти! попробуйте поиграться с настройками графики.")
X(MM_IDS_LOADING_GRAPHICS, "Иницилизирую графику...")
X(MM_IDS_LOADING_INTERFACE, "Загружаю интрефейс...")
X(MM_IDS_LOADING_RACE, "Загружаю трассу...")
X(MM_IDS_208, "Отметка 1")
X(MM_IDS_209, "Отметка 2")
X(MM_IDS_210, "Отметка 3")
X(MM_IDS_211, "Отметка 4")
X(MM_IDS_212, "Отметка 5")
X(MM_IDS_213, "Отметка 6")
X(MM_IDS_214, "Отметка 7")
X(MM_IDS_215, "Отметка 8")
X(MM_IDS_216, "Отметка 9")
X(MM_IDS_217, "Отметка 10")
X(MM_IDS_218, "Отметка 11")
X(MM_IDS_219, "Отметка 12")
X(MM_IDS_220, "Отметка 13")
X(MM_IDS_221, "Отметка 14")
X(MM_IDS_222, "Отметка 15")
X(MM_IDS_223, "Отметка 16")
X(MM_IDS_224, "Отметка 17")
X(MM_IDS_225, "Отметка 18")
X(MM_IDS_226, "Отметка 19")
X(MM_IDS_227, "Отметка 20")
X(MM_IDS_228, "Время круга")
X(MM_IDS_229, "Последний круг!")
X(MM_IDS_230, "System, 16, 22, 0, 700")
X(MM_IDS_231, "System, 20, 40, 0, 700")
X(MM_IDS_232, "System, 16, 22, 0, 700")
X(MM_IDS_233, "Место:  ")
X(MM_IDS_234, "Отметок:  ")
X(MM_IDS_235, "System, 16, 22, 0, 700")
X(MM_IDS_236, "System, 20, 40, 0, 700")
X(MM_IDS_237, "System, 16, 22, 0, 700")
X(MM_IDS_238, "Место:  ")
X(MM_IDS_239, "Отметок:  ")
X(MM_IDS_240, "Круг:  ")
X(MM_IDS_241, "System, 11, 18, 0, 700")
X(MM_IDS_242, "System, 10, 14, 0, 400")
X(MM_IDS_243, "ГАИ")
X(MM_IDS_244, "ЗАСРАНЦЫ")
X(MM_IDS_245, "СИНИЙ")
X(MM_IDS_246, "КРАСНЫЙ")
X(MM_IDS_247, "$")
X(MM_IDS_248, "НЕОПРЕДЕЛЕНО")
X(MM_IDS_249, "Кнопка")
X(MM_IDS_250, "Джой")
X(MM_IDS_251, "Клавиша:")
X(MM_IDS_USE_DI_KEYS, "0")
X(MM_IDS_253, "Изменить камеру")
X(MM_IDS_254, "Внешний вид")
X(MM_IDS_255, "Коробка передач")
X(MM_IDS_256, "Сигнал")
X(MM_IDS_257, "Газ")
X(MM_IDS_258, "Тормоза")
X(MM_IDS_259, "Руль")
X(MM_IDS_260, "Налево")
X(MM_IDS_261, "Направо")
X(MM_IDS_262, "Взгляд вправо")
X(MM_IDS_263, "Взгляд влево")
X(MM_IDS_264, "Взгляд назад")
X(MM_IDS_265, "Взгляд вперед")
X(MM_IDS_266, "Широкий угол")
X(MM_IDS_267, "Приборная панель")
X(MM_IDS_268, "Сдвиг вверх")
X(MM_IDS_269, "Сдвиг вниз")
X(MM_IDS_270, "Реверс")
X(MM_IDS_271, "След. точка")
X(MM_IDS_272, "Пред. точка")
X(MM_IDS_273, "Карта")
X(MM_IDS_274, "Спидометр")
X(MM_IDS_275, "Полоэкр. карта")
X(MM_IDS_276, "Разрешение карты")
X(MM_IDS_277, "CD плеер")
X(MM_IDS_278, "старт/стоп CD")
X(MM_IDS_279, "след. CD трек")
X(MM_IDS_280, "пред. CD трек")
X(MM_IDS_281, "Зеркало задн. вида")
X(MM_IDS_282, "Камера")
X(MM_IDS_283, "Ручник")
X(MM_IDS_284, "Позиция оппонента")
X(MM_IDS_285, "Введите ссобщение")
X(MM_IDS_LEFT_MOUSE_BUTTON, "Левая кнопка")
X(MM_IDS_RIGHT_MOUSE_BUTTON, "Правая кнопка")
X(MM_IDS_MOUSE_X_AXIS, "Мышь X-коорд")
X(MM_IDS_MOUSE_Y_AXIS, "Мышь Y-коорд")
X(MM_IDS_X_AXIS, "X-коорд")
X(MM_IDS_X_AXIS_LEFT, "X-коорд влево")
X(MM_IDS_X_AXIS_RIGHT, "X-коорд вправо")
X(MM_IDS_Y_AXIS, "Y-коорд")
X(MM_IDS_Y_AXIS_UP, "Y-коорд вверх")
X(MM_IDS_Y_AXIS_DOWN, "Y-коорд вниз")
X(MM_IDS_Z_AXIS, "Z-коорд")
X(MM_IDS_U_AXIS, "U-коорд")
X(MM_IDS_R_AXIS, "R-коорд")
X(MM_IDS_V_AXIS, "V-коорд")
X(MM_IDS_POV_AXIS, "POV-коорд")
X(MM_IDS_301, "неизв.")
X(MM_IDS_302, "Моно")
X(MM_IDS_303, "Стерео")
X(MM_IDS_304, "Окружение (не рекомендуется)")
X(MM_IDS_305, "3D звук")
X(MM_IDS_306, "Stereo FX")
X(MM_IDS_307, "Устройств.")
X(MM_IDS_308, "Без веса")
X(MM_IDS_309, "Четверть тона")
X(MM_IDS_310, "Полвина тона")
X(MM_IDS_311, "GOLD MASS")
X(MM_IDS_312, "5 Минут")
X(MM_IDS_313, "10 Минут")
X(MM_IDS_314, "20 Минут")
X(MM_IDS_315, "30 Минут")
X(MM_IDS_316, "100 Очков")
X(MM_IDS_317, "250 Очков")
X(MM_IDS_318, "500 Очков")
X(MM_IDS_319, "1,000 Очков")
X(MM_IDS_320, "ОЧКИ")
X(MM_IDS_321, "ТРАССА")
X(MM_IDS_322, "ВРЕМЯ")
X(MM_IDS_323, "МАШИНА")
X(MM_IDS_324, "Статистика")
X(MM_IDS_325, "ОЧКИ")
X(MM_IDS_326, "ВРЕМЯ")
X(MM_IDS_327, "ТРАССА")
X(MM_IDS_328, "ТРАССА")
X(MM_IDS_329, "ВОДИТЕЛЬ")
X(MM_IDS_330, "ВРЕМЯ")
X(MM_IDS_331, "МАШИНА")
X(MM_IDS_332, "СЕРВЕР ИЛИ ПРИСОЕД. К ИГРЕ")
X(MM_IDS_333, "Утро")
X(MM_IDS_334, "Полдень")
X(MM_IDS_335, "Закат")
X(MM_IDS_336, "Ночь")
X(MM_IDS_337, "Солнечно")
X(MM_IDS_338, "Пасмурно")
X(MM_IDS_339, "Дождь")
X(MM_IDS_340, "Снег")
X(MM_IDS_341, "Com1")
X(MM_IDS_342, "Com2")
X(MM_IDS_343, "Com3")
X(MM_IDS_344, "Com4")
X(MM_IDS_345, "9600")
X(MM_IDS_346, "14400")
X(MM_IDS_347, "38400")
X(MM_IDS_348, "56000")
X(MM_IDS_349, "57600")
X(MM_IDS_350, "115200")
X(MM_IDS_351, "128000")
X(MM_IDS_352, "256000")
X(MM_IDS_353, "1 bit")
X(MM_IDS_354, "1.5 bits")
X(MM_IDS_355, "2 bits")
X(MM_IDS_356, "None")
X(MM_IDS_357, "XOn/XOff")
X(MM_IDS_358, "RTS")
X(MM_IDS_359, "DTR")
X(MM_IDS_360, "RTS/DTR")
X(MM_IDS_361, "No Parity")
X(MM_IDS_362, "Odd")
X(MM_IDS_363, "Even")
X(MM_IDS_364, "Mark")
X(MM_IDS_365, "КЛАСС:")
X(MM_IDS_366, "ПОСЛ. ТРАССА:")
X(MM_IDS_367, "ПОСЛ. МАШИНА:")
X(MM_IDS_368, "УСТРОЙСТВО:")
X(MM_IDS_369, "ИМЯ СЕТИ:")
X(MM_IDS_370, "ОЧКИ:")
X(MM_IDS_371, " - Рекомендовано")
X(MM_IDS_372, "Низк.")
X(MM_IDS_373, "Средн.")
X(MM_IDS_374, "Высок.")
X(MM_IDS_375, "Очень высок.")
X(MM_IDS_376, "%d x %d - Recommended") // u8"%d x %d - Рекомендовано"
X(MM_IDS_377, "Тест")
X(MM_IDS_378, "Наберите сообщение и нажмите ENTER")
X(MM_IDS_379, "Расположение:")
X(MM_IDS_380, "Погода: Ясно")
X(MM_IDS_381, "Погода: Туманно")
X(MM_IDS_382, "Погода: Дождь")
X(MM_IDS_383, "Погода: Снег")
X(MM_IDS_384, "Время: Утро")
X(MM_IDS_385, "Время: Полдень")
X(MM_IDS_386, "Время: Вечер")
X(MM_IDS_387, "Время: Ночь")
X(MM_IDS_388, "Сложность: Любитель")
X(MM_IDS_389, "Сложность: Проффи")
X(MM_IDS_390, "Круги")
X(MM_IDS_391, "Отметки")
X(MM_IDS_392, "Водитель: ")
X(MM_IDS_393, "Маштна: ")
X(MM_IDS_394, "Цвет: ")
X(MM_IDS_395, "Игроков в игре")
X(MM_IDS_396, "ждем сервераt...")
X(MM_IDS_397, "Старт гонки")
X(MM_IDS_398, "ждем сервера...")
X(MM_IDS_399, "Выберите провайдера")
X(MM_IDS_400, ".....")
X(MM_IDS_401, "без имени")
X(MM_IDS_402, "Выберите имя игры.")
X(MM_IDS_403, "Сетевой выбор2")
X(MM_IDS_404, "Создать игру")
X(MM_IDS_405, "Присоедин.")
X(MM_IDS_406, "Настр. звука")
X(MM_IDS_407, "Громкость")
X(MM_IDS_408, "CD громкость")
X(MM_IDS_409, "Баланс")
X(MM_IDS_410, "Чат")
X(MM_IDS_412, "Настр. управления")
X(MM_IDS_413, "Чувствительность")
X(MM_IDS_414, "Мертвая точка")
X(MM_IDS_415, "Педаль")
X(MM_IDS_416, "Чуствительность тормоза")
X(MM_IDS_417, "УПРАВЛЕНИЕ")
X(MM_IDS_418, "ОТЛАДКА")
X(MM_IDS_419, "Позиции")
X(MM_IDS_420, "В ИГРУ")
X(MM_IDS_421, "ВЫ ХОТИТЕ ВЫЙТИ ИЗ ИГРЫ?")
X(MM_IDS_422, "Да")
X(MM_IDS_423, "Нет")
X(MM_IDS_424, "Графика")
X(MM_IDS_425, "ТЕНИ")
X(MM_IDS_426, "ДЕТАЛИЗАЦИЯ")
X(MM_IDS_427, "ДАЛЬНОСТЬ ПРОРИСОВКИ")
X(MM_IDS_428, "КАЧЕСТВО ОСВЕЩЕНИЯ")
X(MM_IDS_429, "Тени от облаков")
X(MM_IDS_430, "Отображение машие")
X(MM_IDS_431, "Текстуры неба")
X(MM_IDS_432, "Перекресн. прорисовка")
X(MM_IDS_433, "Лучш. текстурный фильтр")
X(MM_IDS_PU_KEYS_NAME, "МАППИНГ")
X(MM_IDS_PU_MAIN_NAME, "ГЛАВНОЕ МЕНЮ")
X(MM_IDS_PU_MAIN_RESTART, "Рестарт гонки")
X(MM_IDS_PU_MAIN_OPTIONS, "Настройки")
X(MM_IDS_PU_MAIN_HELP, "Помошь")
X(MM_IDS_PU_MAIN_QUIT, "Выйти в меню гонок")
X(MM_IDS_PU_MAIN_EXIT, "Выйти в Windows")
X(MM_IDS_441, "Пред. меню")
X(MM_IDS_442, "Отмена")
X(MM_IDS_443, "OK")
X(MM_IDS_444, "В игру")
X(MM_IDS_445, "Настройки")
X(MM_IDS_446, "Настр. звука")
X(MM_IDS_447, "Настр. управления")
X(MM_IDS_448, "Настройки графики")
X(MM_IDS_449, "В ИГРУ")
X(MM_IDS_450, "ВЫ ХОТИТЕ ВЫЙТИ ИЗ ГОНКИ?")
X(MM_IDS_451, "Да")
X(MM_IDS_452, "Нет")
X(MM_IDS_PU_RESULTS_NAME, "Результаты")
X(MM_IDS_PU_RESULTS_RESTART, "Рестарт гонки")
X(MM_IDS_PU_RESULTS_NEXT, "След. гонка")
X(MM_IDS_PU_RESULTS_ROSTER, "Список")
X(MM_IDS_PU_RESULTS_QUIT, "Меню гонок")
X(MM_IDS_PU_RESULTS_EXIT, "Выйти в Windows")
X(MM_IDS_459, "Список")
X(MM_IDS_460, "Сервер")
X(MM_IDS_461, "ГАИ")
X(MM_IDS_462, "Засранец")
X(MM_IDS_463, "Красный")
X(MM_IDS_464, "Синий")
X(MM_IDS_465, "0")
X(MM_IDS_466, "System, 14, 14, 0, 400")
X(MM_IDS_467, "System, 14, 14, 0, 400")
X(MM_IDS_468, "System, 14, 14, 0, 400")
X(MM_IDS_469, "System, 14, 14, 0, 400")
X(MM_IDS_470, "System, 14, 14, 0, 400")
X(MM_IDS_471, "System, 14, 14, 0, 400")
X(MM_IDS_472, "System, 14, 14, 0, 400")
X(MM_IDS_473, "System, 14, 14, 0, 400")
X(MM_IDS_474, "System, 14, 14, 0, 400")
X(MM_IDS_475, "System, 14, 14, 0, 400")
X(MM_IDS_476, "System, 14, 14, 0, 400")
X(MM_IDS_477, "System, 14, 14, 0, 400")
X(MM_IDS_478, "System, 14, 14, 0, 400")
X(MM_IDS_479, "System, 14, 14, 0, 400")
X(MM_IDS_480, "System, 18, 38, 0, 400")
X(MM_IDS_481, "Время: , 32, 64, 0, 400")
X(MM_IDS_482, "Низк.")
X(MM_IDS_483, "Сред.")
X(MM_IDS_484, "Высок.")
X(MM_IDS_485, "Оч. высок.")
X(MM_IDS_486, "Ручное")
X(MM_IDS_487, "Автомат.")
X(MM_IDS_488, "Мышь")
X(MM_IDS_489, "Клавиат.")
X(MM_IDS_490, "Джойст.")
X(MM_IDS_491, "Gamepad")
X(MM_IDS_492, "Руль")
X(MM_IDS_493, "Блиц")
X(MM_IDS_494, "По гругу")
X(MM_IDS_495, "С отметками")
X(MM_IDS_496, "Прогулка")
X(MM_IDS_497, "ГАИ и засранцы")
X(MM_IDS_498, "1")
X(MM_IDS_499, "2")
X(MM_IDS_500, "3")
X(MM_IDS_501, "4")
X(MM_IDS_502, "5")
X(MM_IDS_503, "6")
X(MM_IDS_504, "7")
X(MM_IDS_505, "8")
X(MM_IDS_506, "9")
X(MM_IDS_507, "10")
X(MM_IDS_508, "Нет")
X(MM_IDS_509, "Только машины")
X(MM_IDS_510, "Машины и св-ва")
X(MM_IDS_511, "Панель навигиции")
X(MM_IDS_512, "Панель навигиции")
X(MM_IDS_513, "0")
X(MM_IDS_514, "Выкл")
X(MM_IDS_515, "Вкл")
X(MM_IDS_516, "Это приложение требует DirectX 6.1 или выше.")
X(MM_IDS_517, "320")
X(MM_IDS_518, "200")
X(MM_IDS_519, "Переключитесь в 16 bpp и перезапустите приложение.")
X(MM_IDS_520, "%s")
X(MM_IDS_521, " '%s' была найдена. Но в ней отсутствуют многие 3D-фитчи.")
X(MM_IDS_522, " '%s' была найдена. Но в ней отсутствуют многие 3D-фитчи.")
X(MM_IDS_523, "A '%s' была найдена. Но надо хотя бы 2Mb видео памяти")
X(MM_IDS_524, "Програмн. прорис.")
X(MM_IDS_DETECTING_GPU, "Нажмите Ок и игра попытается определить 3D акселератор.")
X(MM_IDS_NO_RENDERERS, "Не обнаружено подходящей видео карты. Приложение не может быть запучено!")

// clang-format on
