/*
    Open1560 - An Open Source Re-Implementation of Midtown Madness 1 Beta
    Copyright (C) 2020 Brick

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

define_dummy_symbol(localize_localize);

#include "localize.h"

#include <algorithm>

struct LangString
{
    u32 Index;
    const char* Value;
};

static constexpr LangString LangStrings[] {
    // clang-format off
    { 1,  "Hello" },
    { 2,  "World" },
    { 3,  "Loading AI railset..." },
    { 4,  "Creating applicable roads map..." },
    { 5,  "Reading race data files..." },
    { 6,  "Creating opponents..." },
    { 7,  "Creating police..." },
    { 8,  "Creating ambients..." },
    { 9,  "Creating pedestrians..." },
    { 10,   "Initializing AI collidables..." },
    { 11,   "Resetting all AI..." },
    { 12,   "Loading city layout..." },
    { 13,   "Loading bangers..." },
    { 14,   "Loading facades..." },
    { 15,   "Gill Sans MT, 12, 24, 0, 400" },
    { 16,   "Gill Sans MT, 12, 16, 0, 400" },
    { 17,   "%d%% complete..." },
    { 18,   "Loading static terrain..." },
    { 19,   "Loading portal information..." },
    { 20,   "Loading collision database..." },
    { 21,   "Player" },
    { 22,   "Loading audio..." },
    { 23,   "Loading city..." },
    { 24,   "Loading player..." },
    { 25,   "Loading AI..." },
    { 26,   "Opp.%d" },
    { 27,   "Loading more audio..." },
    { 28,   "Circuit Race" },
    { 29,   "Checkpoint Race" },
    { 30,   "Blitz Race" },
    { 31,   "Free-for-all" },
    { 32,   "Cops & Robbers" },
    { 33,   "Robbers Teams" },
    { 34,   "Cops & Robbers" },
    { 35,   "Opponent 1" },
    { 36,   "Opponent 2" },
    { 37,   "Opponent 3" },
    { 38,   "Opponent 4" },
    { 39,   "Opponent 5" },
    { 40,   "Opponent 6" },
    { 41,   "Opponent 7" },
    { 42,   "Opponent 8" },
    { 43,   "finished 1st!" },
    { 44,   "finished 2nd" },
    { 45,   "finished 3rd" },
    { 46,   "finished 4th" },
    { 47,   "finished 5th" },
    { 48,   "finished 6th" },
    { 49,   "finished 7th" },
    { 50,   "finished 8th" },
    { 51,   "That didn't happen!" },
    { 52,   "Sleep with the fishes!" },
    { 53,   "Waiting for 1 player" },
    { 54,   "Waiting for 2 players" },
    { 55,   "Waiting for 3 players" },
    { 56,   "Waiting for 4 players" },
    { 57,   "Waiting for 5 players" },
    { 58,   "Waiting for 6 players" },
    { 59,   "Waiting for 7 players" },
    { 60,   "has left the game." },
    { 61,   "The Host has quit." },
    { 62,   "has joined." },
    { 63,   "You have been ejected." },
    { 64,   "Loading remote players..." },
    { 65,   "Gill Sans MT, 16, 32, 0, 400" },
    { 66,   "You finished 1st!" },
    { 67,   "You finished 2nd." },
    { 68,   "You finished 3rd." },
    { 69,   "You finished 4th." },
    { 70,   "You finished 5th." },
    { 71,   "You finished 6th." },
    { 72,   "You finished 7th." },
    { 73,   "You finished 8th." },
    { 74,   "You are a loaf." },
    { 75,   "Ready..." },
    { 76,   "Set..." },
    { 77,   "GO!!" },
    { 78,   "Game Over!" },
    { 79,   "You finished 1st!" },
    { 80,   "You finished 2nd" },
    { 81,   "You finished 3rd" },
    { 82,   "You finished 4th" },
    { 83,   "You finished 5th" },
    { 84,   "You finished 6th" },
    { 85,   "You finished 7th" },
    { 86,   "You finished 8th" },
    { 87,   "You are a loaf." },
    { 88,   "You've just got yourself the Panoz GTR-1!!!" },
    { 89,   "What're you crazy?  You've unlocked the City Bus!!!" },
    { 90,   "You've unlocked the Ford Mustang Cruiser!" },
    { 91,   "You've unlocked the next set of races!!!" },
    { 92,   "Congratulations! You've passed all the Checkpoint races!  Now try PROFESSIONAL!" },
    { 93,   "Congratulations! You've passed all the Checkpoint races!!!" },
    { 94,   "Broadway" },
    { 95,   "Gill Sans MT, 12, 24, 0, 400" },
    { 96,   "Gill Sans MT, 20, 36, 0, 400" },
    { 97,   "Gill Sans MT, 8, 16, 0, 400" },
    { 98,   "---" },
    { 99,   "DriverX" },
    { 100,  "DriverX" },
    { 101,  "Would you like to join an existing game or host one of your own?" },
    { 102,  "has joined." },
    { 103,  "has left." },
    { 104,  "**The Host has quit**" },
    { 105,  "http://www.zone.com/asp/midtredir.asp" },
    { 106,  "Please click on the Midtown Madness icon in the task bar once you have verified connection to the Internet." },
    { 107,  "Please click on the Midtown Madness icon in the task bar once you have verified connection to the Internet." },
    { 108,  "noname" },
    { 109,  "Cops and Robbers" },
    { 110,  "Cruise" },
    { 111,  "Professional" },
    { 112,  "Amateur" },
    { 113,  "ERROR: Host city not installed." },
    { 114,  "ERROR: Network versions do not match." },
    { 115,  "Ready..." },
    { 116,  "Set..." },
    { 117,  "Go!!!" },
    { 118,  "Wait...5 second penalty!" },
    { 119,  "Time's Up!" },
    { 120,  "finished in" },
    { 121,  "Time's Up!" },
    { 122,  "The Host has quit." },
    { 123,  "Ready..." },
    { 124,  "Set..." },
    { 125,  "Go!!!" },
    { 126,  "Wait...5 second penalty!" },
    { 127,  "finished in" },
    { 128,  "Time's Up!" },
    { 129,  "The Host has quit." },
    { 130,  "You dropped the gold!" },
    { 131,  "Go!!!" },
    { 132,  "Wait...5 second penalty!" },
    { 133,  "You have the GOLD!" },
    { 134,  "GOLD DELIVERED!" },
    { 135,  "GOLD DELIVERED!" },
    { 136,  "Time's Up!" },
    { 137,  "Point limit reached" },
    { 138,  "Point limit reached" },
    { 139,  "Point limit reached" },
    { 140,  "COPS" },
    { 141,  "ROBBERS" },
    { 142,  "BLUE" },
    { 143,  "RED" },
    { 144,  "ROBBERS" },
    { 145,  "COPS" },
    { 146,  "BLUE" },
    { 147,  "RED" },
    { 148,  "Time's Up!" },
    { 149,  "Point limit reached" },
    { 150,  "The Host has quit." },
    { 151,  "has the gold!" },
    { 152,  "You have the GOLD!" },
    { 153,  "has the gold!" },
    { 154,  "dropped the gold!" },
    { 155,  "delivered the gold!" },
    { 156,  "20 minutes remaining" },
    { 157,  "15 minutes remaining" },
    { 158,  "10 minutes remaining" },
    { 159,  "5 minutes remaining" },
    { 160,  "1 minute remaining" },
    { 161,  "Go!!!" },
    { 162,  "Wait...5 second penalty!" },
    { 163,  "Ready..." },
    { 164,  "Set..." },
    { 165,  "Go!!!" },
    { 166,  "Wait...5 second penalty!" },
    { 167,  "damaged out" },
    { 168,  "finished in" },
    { 169,  "Time's Up!" },
    { 170,  "The Host has quit." },
    { 171,  "Ready..." },
    { 172,  "Set..." },
    { 173,  "GO!!" },
    { 174,  "Time's Up!" },
    { 175,  "Game Over!" },
    { 176,  "Step into the Panoz GTR-1!!!" },
    { 177,  "Take all your friends for a ride in the City Bus!!!" },
    { 178,  "The Freightliner Century is now available for havoc and mayem." },
    { 179,  "You've beaten all the Blitz races!!" },
    { 180,  "You Won!" },
    { 181,  "Ready..." },
    { 182,  "Set..." },
    { 183,  "GO!!!" },
    { 184,  "Wait...5 second penalty" },
    { 185,  "You finished 1st!" },
    { 186,  "You finished 2nd." },
    { 187,  "You finished 3rd." },
    { 188,  "You finished 4th." },
    { 189,  "You finished 5th." },
    { 190,  "You finished 6th." },
    { 191,  "You finished 7th." },
    { 192,  "You finished 8th." },
    { 193,  "You are a loaf." },
    { 194,  "Take the Panoz GTR-1 for spin.  You've earned it." },
    { 195,  "Who needs exact change?  Now you can DRIVE the City Bus." },
    { 196,  "You got yourself the Ford Mustang Fastback" },
    { 197,  "You are insane!  You've beaten all the Circuit races!" },
    { 198,  "Please switch your desktop to High Color (16-bit) mode before starting Midtown Madness." },
    { 199,  "Please run Redetect Video (in your Midtown Madness folder) and select a different renderer in Graphics Options (Options menu)." },
    { 200,  "Error detected while setting up graphics card." },
    { 201,  "Midtown Madness is already running.  Please activate it from the task bar." },
    { 202,  "Your computer currently has insufficent virtual memory to run this game. This may cause Midtown Madness to perform sluggishly or stop responding. To fix the problem, try freeing up disk space or adjusting your virtual memory settings (Click the Start button, point to Settings, click Control Panel, double-click System, and then click the Performance tab)." },
    { 203,  "You are out or nearly out of disk space right now.  Midtown Madness may not be able to save player or race data.  Please free up some disk space." },
    { 204,  "More video memory required for this screen resolution and/or texture resolution.  Please try different Graphics Options settings (Options menu)." },
    { 205,  "Initializing graphics..." },
    { 206,  "Loading interface..." },
    { 207,  "Loading race..." },
    { 208,  "Checkpoint 1" },
    { 209,  "Checkpoint 2" },
    { 210,  "Checkpoint 3" },
    { 211,  "Checkpoint 4" },
    { 212,  "Checkpoint 5" },
    { 213,  "Checkpoint 6" },
    { 214,  "Checkpoint 7" },
    { 215,  "Checkpoint 8" },
    { 216,  "Checkpoint 9" },
    { 217,  "Checkpoint 10" },
    { 218,  "Checkpoint 11" },
    { 219,  "Checkpoint 12" },
    { 220,  "Checkpoint 13" },
    { 221,  "Checkpoint 14" },
    { 222,  "Checkpoint 15" },
    { 223,  "Checkpoint 16" },
    { 224,  "Checkpoint 17" },
    { 225,  "Checkpoint 18" },
    { 226,  "Checkpoint 19" },
    { 227,  "Checkpoint 20" },
    { 228,  "Lap time" },
    { 229,  "Final lap!" },
    { 230,  "Gill Sans MT, 14, 22, 0, 700" },
    { 231,  "Gill Sans MT, 20, 40, 0, 700" },
    { 232,  "Gill Sans MT, 14, 22, 0, 700" },
    { 233,  "Place:  " },
    { 234,  "Check:  " },
    { 235,  "Gill Sans MT, 16, 22, 0, 700" },
    { 236,  "Gill Sans MT, 20, 40, 0, 700" },
    { 237,  "Gill Sans MT, 16, 22, 0, 700" },
    { 238,  "Place:  " },
    { 239,  "Check:  " },
    { 240,  "Lap:  " },
    { 241,  "Gill Sans MT, 12, 20, 0, 700" },
    { 242,  "Gill Sans MT, 10, 16, 0, 400" },
    { 243,  "COPS" },
    { 244,  "ROBBERS" },
    { 245,  "BLUE" },
    { 246,  "RED" },
    { 247,  "$" },
    { 248,  "UNDEFINED" },
    { 249,  "Button" },
    { 250,  "Joy" },
    { 251,  "Key:" },
    { 252,  "0" },
    { 253,  "Change Camera" },
    { 254,  "External View" },
    { 255,  "Transmission" },
    { 256,  "Horn" },
    { 257,  "Throttle" },
    { 258,  "Brakes" },
    { 259,  "Steering" },
    { 260,  "Steer Left" },
    { 261,  "Steer Right" },
    { 262,  "Look Right" },
    { 263,  "Look Left" },
    { 264,  "Look Back" },
    { 265,  "Look Forward" },
    { 266,  "Wide Angle" },
    { 267,  "Dashboard On/Off" },
    { 268,  "Shift Up" },
    { 269,  "Shift Down" },
    { 270,  "Reverse" },
    { 271,  "Next Waypoint" },
    { 272,  "Prev. Waypoint" },
    { 273,  "Map Toggle" },
    { 274,  "HUD Toggle" },
    { 275,  "Full Screen Map" },
    { 276,  "Map Resolution" },
    { 277,  "Toggle CD Player" },
    { 278,  "Start/Stop CD" },
    { 279,  "Next CD Track" },
    { 280,  "Prev. CD Track" },
    { 281,  "Rear View Mirror" },
    { 282,  "Camera Pan" },
    { 283,  "Handbrake" },
    { 284,  "Opponent Position" },
    { 285,  "Enter Chat Msg" },
    { 286,  "Left Mouse Button" },
    { 287,  "Right Mouse Button" },
    { 288,  "Mouse X-Axis" },
    { 289,  "Mouse Y-Axis" },
    { 290,  "X-Axis" },
    { 291,  "X-Axis Left" },
    { 292,  "X-Axis Right" },
    { 293,  "Y-Axis" },
    { 294,  "Y-Axis Up" },
    { 295,  "Y-Axis Down" },
    { 296,  "Z-Axis" },
    { 297,  "U-Axis" },
    { 298,  "R-Axis" },
    { 299,  "V-Axis" },
    { 300,  "POV-Axis" },
    { 301,  "UNKNOWN - PLEASE REINSTALL" },
    { 302,  "Mono" },
    { 303,  "Stereo" },
    { 304,  "Surround (Not Recommended)" },
    { 305,  "Surround" },
    { 306,  "Stereo FX" },
    { 307,  "Controllers" },
    { 308,  "Weightless" },
    { 309,  "Quarter-Ton" },
    { 310,  "Half-Ton" },
    { 311,  "GOLD MASS" },
    { 312,  "5 Minutes" },
    { 313,  "10 Minutes" },
    { 314,  "20 Minutes" },
    { 315,  "30 Minutes" },
    { 316,  "100 Points" },
    { 317,  "250 Points" },
    { 318,  "500 Points" },
    { 319,  "1,000 Points" },
    { 320,  "POINTS" },
    { 321,  "RACE" },
    { 322,  "TIME" },
    { 323,  "VEHICLE" },
    { 324,  "Race Statistics" },
    { 325,  "SCORE" },
    { 326,  "TIME" },
    { 327,  "RACE" },
    { 328,  "NAME" },
    { 329,  "DRIVER" },
    { 330,  "TIME" },
    { 331,  "VEHICLE" },
    { 332,  "CHOOSE TO HOST OR JOIN A GAME" },
    { 333,  "Morning" },
    { 334,  "Noon" },
    { 335,  "Sunset" },
    { 336,  "Night" },
    { 337,  "Sunny" },
    { 338,  "Cloudy" },
    { 339,  "Raining" },
    { 340,  "Snowing" },
    { 341,  "Com1" },
    { 342,  "Com2" },
    { 343,  "Com3" },
    { 344,  "Com4" },
    { 345,  "9600" },
    { 346,  "14400" },
    { 347,  "38400" },
    { 348,  "56000" },
    { 349,  "57600" },
    { 350,  "115200" },
    { 351,  "128000" },
    { 352,  "256000" },
    { 353,  "1 bit" },
    { 354,  "1.5 bits" },
    { 355,  "2 bits" },
    { 356,  "None" },
    { 357,  "XOn/XOff" },
    { 358,  "RTS" },
    { 359,  "DTR" },
    { 360,  "RTS/DTR" },
    { 361,  "No Parity" },
    { 362,  "Odd" },
    { 363,  "Even" },
    { 364,  "Mark" },
    { 365,  "RANKING:" },
    { 366,  "LAST RACE:" },
    { 367,  "LAST VEHICLE:" },
    { 368,  "CONTROLLER:" },
    { 369,  "NETNAME:" },
    { 370,  "SCORE:" },
    { 371,  " - Recommended" },
    { 372,  "Low" },
    { 373,  "Medium" },
    { 374,  "High" },
    { 375,  "Very High [AGP]" },
    { 376,  "%d x %d - Recommended" },
    { 377,  "Menu Test" },
    { 378,  "Type message here. Press ENTER to send" },
    { 379,  "Locale:" },
    { 380,  "Weather: Clear" },
    { 381,  "Weather: Foggy" },
    { 382,  "Weather: Raining" },
    { 383,  "Weather: Snowing" },
    { 384,  "Time: Morning" },
    { 385,  "Time: Noon" },
    { 386,  "Time: Evening" },
    { 387,  "Time: Night" },
    { 388,  "Difficulty: Amateur" },
    { 389,  "Difficulty: Pro" },
    { 390,  "Laps" },
    { 391,  "Checkpoints" },
    { 392,  "Driver: " },
    { 393,  "Car: " },
    { 394,  "Color: " },
    { 395,  "Players in Session" },
    { 396,  "waiting for host to start..." },
    { 397,  "Start Race" },
    { 398,  "waiting for host to start..." },
    { 399,  "Select Provider" },
    { 400,  "....." },
    { 401,  "noname" },
    { 402,  "Select the game session you'd like to play in." },
    { 403,  "Net Select2" },
    { 404,  "Create Session" },
    { 405,  "Join Session" },
    { 406,  "Audio Options" },
    { 407,  "Wave Volume" },
    { 408,  "CD Volume" },
    { 409,  "Balance" },
    { 410,  "CHAT MENU" },
    { 412,  "Control Options" },
    { 413,  "Steering Sensitivity" },
    { 414,  "Controller Dead Zone" },
    { 415,  "Force-Feedback Scale" },
    { 416,  "Road Force Scale" },
    { 417,  "CONTROL" },
    { 418,  "DEBUG" },
    { 419,  "Record Pos" },
    { 420,  "QUIT MENU" },
    { 421,  "DO YOU WANT TO EXIT THE GAME?" },
    { 422,  "Yes" },
    { 423,  "No" },
    { 424,  "Graphics" },
    { 425,  "SHADOWS" },
    { 426,  "OBJECT DETAIL" },
    { 427,  "FAR CLIP DISTANCE" },
    { 428,  "LIGHTING QUALITY" },
    { 429,  "Cloud Shadows" },
    { 430,  "Vehicle Reflections" },
    { 431,  "Textured Sky" },
    { 432,  "Interlacing" },
    { 433,  "Best Texture Filter" },
    { 434,  "FUNCTION MAPPING" },
    { 435,  "MAIN MENU" },
    { 436,  "Restart Race" },
    { 437,  "Options" },
    { 438,  "Help" },
    { 439,  "Quit to Race Menu" },
    { 440,  "Exit to Windows" },
    { 441,  "Previous Menu" },
    { 442,  "Cancel" },
    { 443,  "OK" },
    { 444,  "Exit Menu" },
    { 445,  "Options" },
    { 446,  "Audio Options" },
    { 447,  "Control Options" },
    { 448,  "Graphics Options" },
    { 449,  "QUIT MENU" },
    { 450,  "DO YOU WANT TO QUIT THE RACE?" },
    { 451,  "Yes" },
    { 452,  "No" },
    { 453,  "Results" },
    { 454,  "Restart Race" },
    { 455,  "Next Race" },
    { 456,  "Show Roster" },
    { 457,  "Race Menu" },
    { 458,  "Exit to Windows" },
    { 459,  "Roster" },
    { 460,  "Host" },
    { 461,  "Cop" },
    { 462,  "Robber" },
    { 463,  "Red" },
    { 464,  "Blue" },
    { 465,  "0" },
    { 466,  "Gill Sans MT, 16, 16, 0, 400" },
    { 467,  "Gill Sans MT, 16, 16, 0, 400" },
    { 468,  "Gill Sans MT, 16, 16, 0, 400" },
    { 469,  "Gill Sans MT, 16, 20, 0, 400" },
    { 470,  "Gill Sans MT, 16, 24, 0, 400" },
    { 471,  "Gill Sans MT, 16, 32, 0, 400" },
    { 472,  "Gill Sans MT, 24, 48, 0, 400" },
    { 473,  "Gill Sans MT, 32, 64, 0, 400" },
    { 474,  "Gill Sans MT, 16, 16, 0, 400" },
    { 475,  "Gill Sans MT, 16, 16, 0, 400" },
    { 476,  "Gill Sans MT, 16, 16, 0, 400" },
    { 477,  "Gill Sans MT, 16, 20, 0, 400" },
    { 478,  "Gill Sans MT, 16, 24, 0, 400" },
    { 479,  "Gill Sans MT, 20, 32, 0, 400" },
    { 480,  "Gill Sans MT, 20, 40, 0, 400" },
    { 481,  "Gill Sans MT, 32, 64, 0, 400" },
    { 482,  "Low" },
    { 483,  "Medium" },
    { 484,  "High" },
    { 485,  "Very High" },
    { 486,  "Manual" },
    { 487,  "Automatic" },
    { 488,  "Mouse" },
    { 489,  "Keyboard" },
    { 490,  "Joystick" },
    { 491,  "Gamepad" },
    { 492,  "Steering Wheel" },
    { 493,  "Blitz" },
    { 494,  "Circuit" },
    { 495,  "Checkpoint" },
    { 496,  "Cruise" },
    { 497,  "Cops and Robbers" },
    { 498,  "1" },
    { 499,  "2" },
    { 500,  "3" },
    { 501,  "4" },
    { 502,  "5" },
    { 503,  "6" },
    { 504,  "7" },
    { 505,  "8" },
    { 506,  "9" },
    { 507,  "10" },
    { 508,  "None" },
    { 509,  "Vehicles Only" },
    { 510,  "Vehicles and Props" },
    { 511,  "Vehicles, Props and Skidmarks" },
    { 512,  "Navigation Bar" },
    { 513,  "0" },
    { 514,  "OFF" },
    { 515,  "ON" },
    { 516,  "This application requires DirectX 6.1 or higher to operate." },
    { 517,  "320" },
    { 518,  "200" },
    { 519,  "Please switch to a 16-bit mode and restart this application." },
    { 520,  "%s" },
    { 521,  "A '%s' video board was found but is not supported because it doesn't have enough video memory and is missing too many 3-D features." },
    { 522,  "A '%s' video board was found but is not supported because it is missing too many 3-D features." },
    { 523,  "A '%s' video board was found but is not supported because it needs at least two MBs of video memory." },
    { 524,  "Software Renderer" },
    { 525,  "Click OK to have Midtown Madness detect the presence of a hardware accelerator card. This may take a few seconds, during which your screen may flicker." },
    { 526,  "No suitable video boards found, application cannot run." },
    // clang-format on
};

LocString* AngelReadString(u32 index)
{
    auto find = std::lower_bound(std::begin(LangStrings), std::end(LangStrings), index,
        [](const LangString& lhs, u32 index) { return lhs.Index < index; });

    const char* result = (find != std::end(LangStrings) && find->Index == index) ? find->Value : "INVALID_LANG_STRING";

    return reinterpret_cast<LocString*>(const_cast<char*>(result));
}
