arts_component "agid3d"
    files {
        -- "d3dlight.cpp",
        -- "d3dlight.h",
        -- "d3dmtldef.cpp",
        -- "d3dmtldef.h",
        "d3dpipe.cpp",
        "d3dpipe.h",
        "d3drpipe.cpp",
        "d3drpipe.h",
        "d3drsys.cpp",
        "d3drsys.h",
        "d3dtexdef.cpp",
        "d3dtexdef.h",
        "d3dview.cpp",
        "d3dview.h",
        "ddbitmap.cpp",
        "ddbitmap.h",
        "dderror.cpp",
        "dderror.h",
        "ddpipe.cpp",
        "ddpipe.h",
        -- "pcpipe.cpp",
        -- "pcpipe.h",
    }
