arts_component "mmanim"
    files {
        "AnimDOF.cpp",
        "AnimDOF.h",
        "AnimMgr.cpp",
        "AnimMgr.h",
        -- "AnimSpline.cpp",
        -- "AnimSpline.h",
        -- "AnimTrigger.cpp",
        -- "AnimTrigger.h",
        -- "Excel.cpp",
        -- "Excel.h",
        -- "boat.cpp",
        -- "boat.h",
        -- "bridge.cpp",
        -- "bridge.h",
        -- "mmbridgeaudmgr.cpp",
        -- "mmbridgeaudmgr.h",
        -- "plane.cpp",
        -- "plane.h",
        -- "train.cpp",
        -- "train.h",
        -- "traincar.cpp",
        -- "traincar.h",
    }
