arts_component "agi"
    files {
        "bitmap.cpp",
        "bitmap.h",
        "cmodel.cpp",
        "cmodel.h",
        -- "cmodel8.cpp",
        -- "cmodel8.h",
        "cmodelx.cpp",
        "cmodelx.h",
        -- "dlp.cpp",
        -- "dlp.h",
        -- "dlptmpl.cpp",
        -- "dlptmpl.h",
        -- "dyndlp.cpp",
        -- "dyndlp.h",
        "error.cpp",
        "error.h",
        "getdlp.cpp",
        "getdlp.h",
        "light.cpp",
        "light.h",
        -- "lmodel.cpp",
        -- "lmodel.h",
        -- "mtldef.cpp",
        -- "mtldef.h",
        "mtllib.cpp",
        "mtllib.h",
        "palette.cpp",
        "palette.h",
        "physdef.cpp",
        "physdef.h",
        "physlib.cpp",
        "physlib.h",
        "pipeline.cpp",
        "pipeline.h",
        "print.cpp",
        "print.h",
        "refresh.cpp",
        "refresh.h",
        "render.cpp",
        "render.h",
        "rsys.cpp",
        "rsys.h",
        -- "smap.cpp",
        -- "smap.h",
        "surface.cpp",
        "surface.h",
        "texdef.cpp",
        "texdef.h",
        "texlib.cpp",
        "texlib.h",
        "viewport.cpp",
        "viewport.h",

        "rgba.h",
        "agilib.h",
        "vertex.h",
    }
